### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by qgallouedec** [perezjln/gym-lowcostrobot#2]
- [x] Make the environment deterministic (https://github.com/perezjln/gym-lowcostrobot/commit/7b03b466e5776f34948d8300102bd3ebda200621) #8
- [x] Documentation #8
- [x] Find the correct fps (https://github.com/perezjln/gym-lowcostrobot/commit/c3ab416896274f4218ee342100b177976fab32cd)
- [x] Proper support for rendering (use `render_mode` instead of `do_render`) (https://github.com/perezjln/gym-lowcostrobot/commit/416c8e67bc50f3104372e73e202f21404cb29c14 https://github.com/perezjln/gym-lowcostrobot/commit/c3ab416896274f4218ee342100b177976fab32cd)
- [x] Find limits for the observation space #8
- [x] Improve readability for distance/reward (#3)
